services:
  - type: web
    name: matali-pricing
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app_v2.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
